name: e2e-tests

on:
  push:
    branches:
      - main

jobs:
  basic-ubuntu-22:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress tests
        uses: ./
        with:
          working-directory: examples/basic
          build: npx cypress infoowser chrome --spec "*.cy.js"
